name: Release and Publish

on:
  push:
    tags:
      - 'v*' # ex: "v1.0"

jobs:
  style_check:
    name: Style Check
    uses: ./.github/workflows/style-check.yml

  run_tests:
    name: Run Tests
    uses: ./.github/workflows/build-test.yml

  build_source:
    name: Build Sources
    runs-on: ubuntu-latest
    needs:
      - style_check
      - run_tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"
      - name: Install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build source tarball
        run: python -m build --sdist --outdir dist
      - name: Upload source tarball
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build Wheels
    runs-on: ubuntu-latest
    needs:
      - style_check
      - run_tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - name: Build pure Python wheels
        run: pip wheel . -w wheels/ --no-deps
      - name: Upload builds
        uses: actions/upload-artifact@v3
        with:
          path: ./wheels/*.whl

  publish_to_pypi:
    name: Publish to PyPI
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build_source
      - build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download source tarball and builds
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }} # TODO: Add token in github settings
